### ISSUE TITLE
proguard

### ISSUE THREAD

**Issue by creativetrendsapps** [DroidsOnRoids/Casty#13]
my app crashes using this library with proguard

07-24 03:05:46.995 25441-25441/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.creativetrends.simple.app.pro, PID: 25441
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.creativetrends.simple.app.pro/com.creativetrends.simple.app.pro.main.VideoActivity}: java.lang.IllegalStateException: Failed to initialize CastContext.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2690)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2755)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6196)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
     Caused by: java.lang.IllegalStateException: Failed to initialize CastContext.
        at com.google.android.gms.cast.framework.CastContext.zzbu(Unknown Source)
        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
        at pl.droidsonroids.casty.a.<init>(Unknown Source)
        at pl.droidsonroids.casty.a.a(Unknown Source)
        at com.creativetrends.simple.app.pro.main.VideoActivity.onCreate(Unknown Source)
        at android.app.Activity.performCreate(Activity.java:6698)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2643)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2755) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6196) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) 
     Caused by: java.lang.ClassNotFoundException: pl.droidsonroids.casty.CastOptionsProvider
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at java.lang.Class.forName(Class.java:326)
        at com.google.android.gms.cast.framework.CastContext.zzbu(Unknown Source) 
        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source) 
        at pl.droidsonroids.casty.a.<init>(Unknown Source) 
        at pl.droidsonroids.casty.a.a(Unknown Source) 
        at com.creativetrends.simple.app.pro.main.VideoActivity.onCreate(Unknown Source) 
        at android.app.Activity.performCreate(Activity.java:6698) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2643) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2755) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6196) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "pl.droidsonroids.casty.CastOptionsProvider" on path: DexPathList[[zip file "/data/app/com.creativetrends.simple.app.pro-2/base.apk"],nativeLibraryDirectories=[/data/app/com.creativetrends.simple.app.pro-2/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:400) 
        at java.lang.Class.forName(Class.java:326) 
        at com.google.android.gms.cast.framework.CastContext.zzbu(Unknown Source) 
        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source) 
        at pl.droidsonroids.casty.a.<init>(Unknown Source) 
        at pl.droidsonroids.casty.a.a(Unknown Source) 
        at com.creativetrends.simple.app.pro.main.VideoActivity.onCreate(Unknown Source) 
        at android.app.Activity.performCreate(Activity.java:6698) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2643) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2755) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6196) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by creativetrendsapps** [comment]
fixed by adding -keep class pl.droidsonroids.casty.** { *; }

**Comment by koral--** [comment]
Thanks @creativetrendsapps indeed it works but the proper solution seems to be to add consumer proguard files to library. In such case users won't need to add rules on their own.
WDYT @burnoo ?
