### ISSUE TITLE
RemoteServiceException$ForegroundServiceDidNotStartInTimeException

### ISSUE THREAD

**Issue by ashishdcafe** [DroidsOnRoids/Casty#19]
Hi, getting below error

android.app.StackTrace: Last startServiceCommon() call for this service was made here
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1876)
    at android.app.ContextImpl.startForegroundService(ContextImpl.java:1831)
    at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:779)
    at com.google.android.gms.internal.cast.zzah.zzg
    at com.google.android.gms.internal.cast.zzah.onQueueStatusUpdated
    at com.google.android.gms.cast.framework.media.zzr.onQueueStatusUpdated
    at com.google.android.gms.internal.cast.zzdn.onQueueStatusUpdated
    at com.google.android.gms.internal.cast.zzdn.zzp
    at com.google.android.gms.cast.framework.media.RemoteMediaClient.onMessageReceived
    at com.google.android.gms.internal.cast.zzcz.run
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.google.android.gms.internal.cast.zzep.dispatchMessage
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{92d22a8 u0 com.xyz/com.google.android.gms.cast.framework.media.MediaNotificationService}
    at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:1965)
    at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1936)
    at android.app.ActivityThread.access$2700(ActivityThread.java:256)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2190)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
    
    OS: Android 12
    Device: Pixel 6 Pro

**Comment by koral--** [comment]
This project is no longer maintained.
